"""
Prometheus metrics middleware and collectors.

Why Prometheus in production?
    - Real-time visibility into request rates, latencies, and error rates
    - Histograms let you compute p50/p95/p99 latencies
    - Counters track throughput and error budgets
    - Alertmanager can page on-call when error_rate > threshold
    - Grafana dashboards give the whole team a shared view
"""

from __future__ import annotations

import time
from typing import Callable

from fastapi import FastAPI, Request, Response
from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    generate_latest,
    CONTENT_TYPE_LATEST,
)
from starlette.middleware.base import BaseHTTPMiddleware

from utils.logger import logger

# ── Metric Definitions ───────────────────────────────────────────────

# HTTP metrics
http_requests_total = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status_code"],
)

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "endpoint"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

http_requests_in_flight = Gauge(
    "http_requests_in_flight",
    "Number of HTTP requests currently being processed",
)

# RAG pipeline metrics
rag_retrieval_duration_seconds = Histogram(
    "rag_retrieval_duration_seconds",
    "Time spent retrieving context chunks",
    ["fallback_used"],
    buckets=[0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0],
)

rag_generation_duration_seconds = Histogram(
    "rag_generation_duration_seconds",
    "Time spent generating LLM responses",
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 40.0],
)

rag_queries_total = Counter(
    "rag_queries_total",
    "Total RAG queries processed",
    ["result"],  # "success", "fallback", "no_context", "error"
)

rag_input_tokens = Counter(
    "rag_input_tokens_total",
    "Total input tokens sent to LLM",
)

rag_output_tokens = Counter(
    "rag_output_tokens_total",
    "Total output tokens generated by LLM",
)

# Document metrics
documents_uploaded_total = Counter(
    "documents_uploaded_total",
    "Total documents uploaded",
    ["type"],  # pdf, txt, csv
)

documents_chunks_total = Gauge(
    "documents_chunks_total",
    "Total document chunks stored in vector DB",
)

# Embedding metrics
embeddings_generated_total = Counter(
    "embeddings_generated_total",
    "Total embedding vectors generated",
)

embeddings_errors_total = Counter(
    "embeddings_errors_total",
    "Total embedding generation errors",
)

# Cache metrics
cache_hits_total = Counter(
    "cache_hits_total",
    "Total cache hits",
    ["backend"],  # "lru", "redis"
)

cache_misses_total = Counter(
    "cache_misses_total",
    "Total cache misses",
)

# Feedback metrics
feedback_total = Counter(
    "feedback_total",
    "Total user feedback submissions",
    ["rating"],  # "positive", "negative"
)

# Database health
db_connection_healthy = Gauge(
    "db_connection_healthy",
    "Whether the database connection is healthy (1=ok, 0=down)",
)


# ── Middleware ───────────────────────────────────────────────────────


class PrometheusMiddleware(BaseHTTPMiddleware):
    """
    Collects HTTP metrics for every request.

    Records:
        - Request count by method, endpoint, status
        - Request duration histogram
        - In-flight request gauge
    """

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        http_requests_in_flight.inc()

        start = time.monotonic()
        response = await call_next(request)
        elapsed = time.monotonic() - start

        http_requests_in_flight.dec()

        # Normalise endpoint: replace path params with placeholders
        endpoint = request.url.path
        for param_name, _ in request.path_params.items():
            endpoint = endpoint.replace(
                request.path_params[param_name], f"{{{param_name}}}"
            )

        http_requests_total.labels(
            method=request.method,
            endpoint=endpoint,
            status_code=response.status_code,
        ).inc()

        http_request_duration_seconds.labels(
            method=request.method, endpoint=endpoint
        ).observe(elapsed)

        return response


# ── Prometheus endpoint ──────────────────────────────────────────────


def mount_metrics_endpoint(app: FastAPI) -> None:
    """
    Add a GET /metrics endpoint that Prometheus scrapes.

    Usage in main.py::

        mount_metrics_endpoint(app)
    """

    @app.get("/metrics", tags=["Monitoring"])
    async def metrics():
        return Response(
            content=generate_latest(),
            media_type=CONTENT_TYPE_LATEST,
        )

    logger.info("Prometheus metrics endpoint mounted at /metrics")


# ── Helpers ──────────────────────────────────────────────────────────


def record_rag_query(
    retrieval_ms: float,
    generation_ms: float,
    input_tokens: int,
    output_tokens: int,
    fallback_used: bool,
    success: bool = True,
    error: bool = False,
    no_context: bool = False,
) -> None:
    """Record a RAG query to all relevant metrics."""
    rag_retrieval_duration_seconds.labels(
        fallback_used=str(fallback_used).lower()
    ).observe(retrieval_ms / 1000)

    rag_generation_duration_seconds.observe(generation_ms / 1000)

    if error:
        result = "error"
    elif no_context:
        result = "no_context"
    elif fallback_used:
        result = "fallback"
    else:
        result = "success"

    rag_queries_total.labels(result=result).inc()
    rag_input_tokens.inc(input_tokens)
    rag_output_tokens.inc(output_tokens)


def record_feedback(rating: float) -> None:
    """Record user feedback to metrics."""
    label = "positive" if rating > 0 else "negative"
    feedback_total.labels(rating=label).inc()


def record_document_upload(file_type: str, chunks: int) -> None:
    """Record a document upload."""
    documents_uploaded_total.labels(type=file_type).inc()
    documents_chunks_total.inc(chunks)


def record_embedding(count: int) -> None:
    """Record embedding generation."""
    embeddings_generated_total.inc(count)


def record_embedding_error() -> None:
    """Record an embedding error."""
    embeddings_errors_total.inc()


def record_cache_hit(backend: str) -> None:
    """Record a cache hit."""
    cache_hits_total.labels(backend=backend).inc()


def record_cache_miss() -> None:
    """Record a cache miss."""
    cache_misses_total.inc()


def set_db_healthy(healthy: bool) -> None:
    """Set the database health gauge."""
    db_connection_healthy.set(1 if healthy else 0)


# ── Evaluation metrics ───────────────────────────────────────────────

ev_faithfulness = Histogram(
    "rag_eval_faithfulness",
    "RAGAS faithfulness score (0-1)",
    buckets=[0.1, 0.3, 0.5, 0.7, 0.8, 0.9, 0.95, 1.0],
)

ev_answer_relevancy = Histogram(
    "rag_eval_answer_relevancy",
    "RAGAS answer relevancy score (0-1)",
    buckets=[0.1, 0.3, 0.5, 0.7, 0.8, 0.9, 0.95, 1.0],
)

ev_context_recall = Histogram(
    "rag_eval_context_recall",
    "RAGAS context recall score (0-1)",
    buckets=[0.1, 0.3, 0.5, 0.7, 0.8, 0.9, 0.95, 1.0],
)

ev_context_precision = Histogram(
    "rag_eval_context_precision",
    "RAGAS context precision score (0-1)",
    buckets=[0.1, 0.3, 0.5, 0.7, 0.8, 0.9, 0.95, 1.0],
)

# Application info
app_info = Gauge("app_info", "Application metadata", ["version", "environment"])
