-- ============================================================================
-- RAG FAQ Chatbot — Complete Supabase Database Schema
-- ============================================================================
-- Run this in the Supabase SQL Editor (one statement at a time or all at once).
-- Database: Supabase PostgreSQL 17 with pgvector
-- ============================================================================

-- 1. Enable Extensions ─────────────────────────────────────────────────────
-- pgvector adds the `vector` type and distance operators (<=>, <#>, <+>)
-- pgcrypto enables gen_random_uuid() for default UUID generation
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;


-- 2. Documents Table ───────────────────────────────────────────────────────
-- Stores one row per text chunk extracted from uploaded PDFs/TXTs.
-- The `embedding` column uses the vector type for cosine similarity search.
-- metadata is a JSONB column for flexible key-value storage (source, page, etc.)
CREATE TABLE IF NOT EXISTS documents (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    filename    TEXT        NOT NULL,
    chunk_index INTEGER     NOT NULL DEFAULT 0,
    content     TEXT        NOT NULL,
    embedding   vector(384)  NOT NULL,   -- all-MiniLM-L6-v2 outputs 384-dim vectors
    metadata    JSONB       DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index on filename for quick listing of chunks by document
CREATE INDEX IF NOT EXISTS ix_documents_filename
    ON documents (filename);

-- Composite index for retrieving chunks of a file in order
CREATE INDEX IF NOT EXISTS ix_documents_filename_chunk
    ON documents (filename, chunk_index);

-- Index on created_at for filtering recent uploads
CREATE INDEX IF NOT EXISTS ix_documents_created_at
    ON documents (created_at DESC);

-- ============================================================================
-- 2b. Vector Index (only after inserting data)
-- ============================================================================
-- pgvector supports two index types:
--   • ivfflat    — approximate, faster but less accurate (good for >100k rows)
--   • hnsw       — newer, faster builds, better recall (recommended for <1M rows)
--
-- The index is created separately AFTER data is loaded so it can calculate
-- the correct index parameters. Run this once you have at least a few rows.
-- ============================================================================

-- Uncomment after inserting at least ~1000 chunks:
-- CREATE INDEX IF NOT EXISTS ix_documents_embedding_hnsw
--     ON documents
--     USING hnsw (embedding vector_cosine_ops)
--     WITH (m = 16, ef_construction = 200);


-- 3. Chat History Table ────────────────────────────────────────────────────
-- Each row is one message (user or assistant) in a conversation.
-- `session_id` groups messages; generated by the frontend (UUID string).
CREATE TABLE IF NOT EXISTS chat_history (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  TEXT        NOT NULL,
    role        TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
    message     TEXT        NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Composite index for retrieving a session's history in chronological order.
-- This is the most-used query: "SELECT * WHERE session_id = ? ORDER BY timestamp"
CREATE INDEX IF NOT EXISTS ix_chat_history_session_ts
    ON chat_history (session_id, timestamp);

-- Index for counting messages per session (useful for dashboard analytics)
CREATE INDEX IF NOT EXISTS ix_chat_history_session_id
    ON chat_history (session_id);

-- Index on timestamp for global feeds or admin views
CREATE INDEX IF NOT EXISTS ix_chat_history_ts
    ON chat_history (timestamp DESC);


-- 4. Feedback Table ────────────────────────────────────────────────────────
-- User ratings (thumbs up = +1.0, thumbs down = -1.0) on assistant messages.
-- CASCADE delete: if a chat message is deleted, its feedback is removed too.
CREATE TABLE IF NOT EXISTS feedback (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id  UUID        NOT NULL REFERENCES chat_history(id) ON DELETE CASCADE,
    rating      FLOAT       NOT NULL CHECK (rating >= -1.0 AND rating <= 1.0),
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for looking up feedback by message (the most common query)
CREATE INDEX IF NOT EXISTS ix_feedback_message_id
    ON feedback (message_id);

-- Index for rolling up ratings (e.g., average rating per message)
CREATE INDEX IF NOT EXISTS ix_feedback_rating
    ON feedback (rating);

-- Index for time-based analytics (feedback over time)
CREATE INDEX IF NOT EXISTS ix_feedback_created_at
    ON feedback (created_at DESC);


-- 5. Document Storage Bucket ───────────────────────────────────────────────
-- Supabase Storage keeps the original PDF/TXT files separate from the DB.
-- We create a bucket + policies so the frontend can upload/download files.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'documents',
    'documents',
    FALSE,                  -- not public; access controlled via policies
    20 * 1024 * 1024,       -- 20 MB max file size
    ARRAY['application/pdf', 'text/plain']
)
ON CONFLICT (id) DO NOTHING;


-- 6. Row Level Security ────────────────────────────────────────────────────

-- ── 6a. documents table ───────────────────────────────────────────────────
-- Enable RLS on all three application tables
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- Server-side code uses the service_role key (bypasses RLS), so for now
-- we keep policies permissive and control access at the API layer.
-- In production with direct client access, tighten these.

-- Anyone can read document chunks (needed for similarity search results)
-- In production: restrict this to authenticated users if needed.
CREATE POLICY "documents_select" ON documents
    FOR SELECT
    USING (true);

-- Only service_role (backend) can insert/update/delete
CREATE POLICY "documents_insert" ON documents
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "documents_update" ON documents
    FOR UPDATE
    USING (true);

CREATE POLICY "documents_delete" ON documents
    FOR DELETE
    USING (true);


-- ── 6b. chat_history table ────────────────────────────────────────────────
-- Users can read messages from their own sessions
-- In production: add WHERE session_id = auth.uid() or similar
CREATE POLICY "chat_history_select" ON chat_history
    FOR SELECT
    USING (true);

CREATE POLICY "chat_history_insert" ON chat_history
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "chat_history_update" ON chat_history
    FOR UPDATE
    USING (true);

CREATE POLICY "chat_history_delete" ON chat_history
    FOR DELETE
    USING (true);


-- ── 6c. feedback table ────────────────────────────────────────────────────
-- Users can read and create feedback for any message
CREATE POLICY "feedback_select" ON feedback
    FOR SELECT
    USING (true);

CREATE POLICY "feedback_insert" ON feedback
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "feedback_update" ON feedback
    FOR UPDATE
    USING (true);

CREATE POLICY "feedback_delete" ON feedback
    FOR DELETE
    USING (true);


-- 7. Storage Policies ──────────────────────────────────────────────────────
-- Define who can read/write files in the 'documents' bucket.
-- The backend uploads via service_role key → bypasses RLS entirely.
-- These policies are for direct client-side access if needed later.

-- Allow reading by anyone (for serving document previews)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'storage_documents_select' AND schemaname = 'storage') THEN
        CREATE POLICY "storage_documents_select" ON storage.objects FOR SELECT USING (bucket_id = 'documents');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'storage_documents_insert' AND schemaname = 'storage') THEN
        CREATE POLICY "storage_documents_insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'documents');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'storage_documents_delete' AND schemaname = 'storage') THEN
        CREATE POLICY "storage_documents_delete" ON storage.objects FOR DELETE USING (bucket_id = 'documents');
    END IF;
END $$;


-- 8. match_documents() — pgvector Cosine Similarity Search ─────────────────
-- This function is the heart of the RAG pipeline.
-- Given a 384-dim embedding vector, it returns the top-K most similar chunks
-- using cosine distance (<=> operator).
--
-- Cosine similarity = 1 - cosine_distance
-- Lower distance = more similar     → ORDER BY ... <=> ... ASC
--
-- Called from backend via: supabase.rpc('match_documents', {...})
CREATE OR REPLACE FUNCTION match_documents(
    query_embedding vector(384),
    match_count     INT DEFAULT 5,
    similarity_threshold FLOAT DEFAULT 0.0
)
RETURNS TABLE (
    id          UUID,
    filename    TEXT,
    chunk_index INT,
    content     TEXT,
    similarity  FLOAT,
    metadata    JSONB
)
LANGUAGE plpgsql
STABLE
PARALLEL SAFE
AS $$
BEGIN
    RETURN QUERY
    SELECT
        d.id,
        d.filename,
        d.chunk_index,
        d.content,
        1 - (d.embedding <=> query_embedding) AS similarity,
        d.metadata
    FROM documents d
    WHERE 1 - (d.embedding <=> query_embedding) >= similarity_threshold
    ORDER BY d.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- The function is STABLE (same input → same output within a transaction)
-- and PARALLEL SAFE so pgvector can parallelize the scan across indexes.


-- 9. Helper: delete_all_documents() ────────────────────────────────────────
-- Convenience function to wipe all chunks (useful during development).
CREATE OR REPLACE FUNCTION delete_all_documents()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    deleted_count INT;
BEGIN
    DELETE FROM documents
    WHERE id IS NOT NULL
    RETURNING count(*) INTO deleted_count;

    RETURN format('Deleted %s document chunks.', deleted_count);
END;
$$;


-- 10. Helper: get_session_stats() ──────────────────────────────────────────
-- Dashboard query: session count, message count, avg messages per session.
CREATE OR REPLACE FUNCTION get_session_stats()
RETURNS TABLE (
    total_sessions  BIGINT,
    total_messages  BIGINT,
    avg_msg_per_session NUMERIC,
    total_documents BIGINT,
    total_feedback  BIGINT,
    avg_rating      NUMERIC
)
LANGUAGE plpgsql
STABLE
PARALLEL SAFE
AS $$
BEGIN
    RETURN QUERY
    SELECT
        (SELECT count(DISTINCT session_id) FROM chat_history) AS total_sessions,
        (SELECT count(*) FROM chat_history) AS total_messages,
        (SELECT ROUND(count(*)::NUMERIC / NULLIF(count(DISTINCT session_id), 0), 1)
         FROM chat_history) AS avg_msg_per_session,
        (SELECT count(DISTINCT filename) FROM documents) AS total_documents,
        (SELECT count(*) FROM feedback) AS total_feedback,
        (SELECT ROUND(avg(rating)::NUMERIC, 2) FROM feedback) AS avg_rating;
END;
$$;


-- 11. Sample Data ──────────────────────────────────────────────────────────
-- Run these inserts to verify the schema works end-to-end.

-- Sample document chunks (manually pre-embedded for testing — real embeddings
-- would be 384 floats, here we use placeholder vectors for schema validation)

-- Note: These are NOT real embeddings, just 384-dim zero vectors.
-- The backend creates real embeddings via sentence-transformers.
-- Remove these after verifying schema integrity.

/*
INSERT INTO documents (filename, chunk_index, content, embedding)
VALUES
    (
        'faq-company.pdf',
        0,
        'Our company was founded in 2020 and provides AI-powered customer support solutions to over 500 businesses worldwide.',
        array_fill(0::float, ARRAY[384])
    ),
    (
        'faq-company.pdf',
        1,
        'We offer a 30-day free trial for all plans. No credit card is required. You can cancel anytime during the trial period.',
        array_fill(0::float, ARRAY[384])
    ),
    (
        'faq-company.pdf',
        2,
        'Our support team is available 24/7 via live chat and email. Average response time is under 5 minutes for paid plans.',
        array_fill(0::float, ARRAY[384])
    ),
    (
        'pricing-guide.txt',
        0,
        'Basic plan: $29/month for up to 3 agents. Pro plan: $99/month for up to 10 agents. Enterprise: custom pricing.',
        array_fill(0::float, ARRAY[384])
    ),
    (
        'pricing-guide.txt',
        1,
        'All plans include unlimited conversations, basic analytics, and email support. Pro and Enterprise include priority support.',
        array_fill(0::float, ARRAY[384])
    );

-- Sample chat history
INSERT INTO chat_history (session_id, role, message)
VALUES
    ('session-abc-001', 'user', 'What plans do you offer?'),
    ('session-abc-001', 'assistant', 'We offer three plans: Basic ($29/mo for 3 agents), Pro ($99/mo for 10 agents), and Enterprise (custom pricing). All plans include unlimited conversations and email support.'),
    ('session-abc-001', 'user', 'Is there a free trial?'),
    ('session-abc-001', 'assistant', 'Yes! We offer a 30-day free trial for all plans. No credit card is required, and you can cancel anytime.'),
    ('session-xyz-002', 'user', 'What are your support hours?'),
    ('session-xyz-002', 'assistant', 'Our support team is available 24/7 via live chat and email, with an average response time under 5 minutes for paid plans.');

-- Sample feedback
INSERT INTO feedback (message_id, rating, comment)
VALUES
    ('<paste-assistant-message-uuid-here>', 1.0, 'Very helpful and accurate answer!'),
    ('<paste-another-message-uuid-here>', -1.0, 'The answer was too generic.');
*/

-- ============================================================================
-- End of migration
-- ============================================================================
--
-- Quick reference — common queries:
--
-- • Search for similar documents:
--   SELECT * FROM match_documents(query_embedding => '[0.1, 0.2, ...]'::vector(384), match_count => 5);
--
-- • Get conversation history for a session:
--   SELECT * FROM chat_history WHERE session_id = 'my-session' ORDER BY timestamp;
--
-- • Get average rating for all messages:
--   SELECT message_id, ROUND(AVG(rating)::numeric, 2) AS avg_rating FROM feedback GROUP BY message_id;
--
-- • Delete all chunks from a specific file:
--   DELETE FROM documents WHERE filename = 'old-file.pdf';
--
-- • Check document count per file:
--   SELECT filename, count(*) AS chunks FROM documents GROUP BY filename ORDER BY chunks DESC;
